@startuml
class Pizza {
    + Name : string <<get>> <<set>>
    + Details : string <<get>> <<set>>
    + Price : double <<get>> <<set>>
    + Img : string <<get>> <<set>>
    + Pizza()
    + {static} GetAvailablePizzas() : dynamic
    + CalculatePizzaPrice() : void
    + <<override>> ToString() : string
}
class "ObservableCollection`1"<T> {
}
Pizza --> "Size" Size
Pizza --> "Toppings<Topping>" "ObservableCollection`1"
@enduml
