@startuml
class Pizza {
    + Name : string <<get>> <<set>>
    + Details : string <<get>> <<set>>
    + Size : string <<get>> <<set>>
    + Price : double <<get>> <<set>>
    + Photo : string <<get>> <<set>>
}
class "List`1"<T> {
}
Pizza --> "Toppings<Topping>" "List`1"
@enduml
