@startuml
class Size {
    + Name : string <<get>> <<set>>
    + Price : double <<get>> <<set>>
    + {static} GetAvailableSizes() : ObservableCollection<Size>
    + <<override>> ToString() : string
}
@enduml
