@startuml
class Order {
    + <<virtual>> Items : ObservableCollection<Pizza>? <<get>> <<set>>
    + Total : double <<get>> <<set>>
    + Customer : User? <<get>> <<set>>
    + CalculateTotal() : void
}
Order --> "Id" Guid
Order o-> "OrderDate" DateTime
@enduml
