@startuml
class Order {
    + Total : double <<get>> <<set>>
    + Customer : User? <<get>> <<set>>
}
class "ObservableCollection`1"<T> {
}
Order --> "Id" Guid
Order --> "Items<Pizza>" "ObservableCollection`1"
Order --> "OrderDate" DateTime
@enduml
