@startuml
class Pizza {
    + Name : string <<get>> <<set>>
    + Price : double <<get>> <<set>>
    + Details : string? <<get>> <<set>>
    + Img : string? <<get>> <<set>>
    + IsCatalouge : bool <<get>> <<set>> = false
    + CrustSize : CrustSize? <<get>> <<set>>
    + <<virtual>> Toppings : ObservableCollection<Topping>? <<get>> <<set>>
    + <<virtual>> Orders : ObservableCollection<Order>? <<get>> <<set>>
    + CalculatePizzaPrice() : void
    + <<override>> ToString() : string
}
Pizza o-> "Id" Guid
@enduml
