@startuml
class Pizza {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Details : string? <<get>> <<set>>
    + <<virtual>> Size : CrustSize? <<get>> <<set>>
    + Price : double <<get>> <<set>>
    + <<virtual>> Toppings : ObservableCollection<Topping>? <<get>> <<set>>
    + Img : string? <<get>> <<set>>
    + <<virtual>> Orders : ObservableCollection<Order>? <<get>> <<set>>
    + CalculatePizzaPrice() : void
    + <<override>> ToString() : string
}
@enduml
